import type { SeedBankPart, SeedItem } from "./types";

/**
 * Starter grammar items, 13 per CEFR level: 8 single choice and 5 gap fill.
 * The correct option position is spread evenly (two per letter per level).
 */

type Level = SeedItem["level"];
type Within = NonNullable<SeedItem["within"]>;
type OptionId = "a" | "b" | "c" | "d";

function choice(
  level: Level,
  skill: string,
  within: Within,
  prompt: string,
  options: [string, string, string, string],
  correct: OptionId,
  explanation: string,
): SeedItem {
  const ids: OptionId[] = ["a", "b", "c", "d"];
  return {
    section: "GRAMMAR",
    level,
    type: "SINGLE_CHOICE",
    skillTag: `grammar.${skill}`,
    within,
    prompt,
    content: { kind: "CHOICE", options: options.map((text, i) => ({ id: ids[i], text })) },
    key: { kind: "CHOICE", correct: [correct] },
    explanation,
  };
}

type GapSpec = { id: string; answers: string[]; choices?: string[] };

function gap(
  level: Level,
  skill: string,
  within: Within,
  prompt: string,
  gaps: GapSpec[],
  explanation: string,
): SeedItem {
  return {
    section: "GRAMMAR",
    level,
    type: "GAP_FILL",
    skillTag: `grammar.${skill}`,
    within,
    prompt,
    content: {
      kind: "GAP",
      gaps: gaps.map((g) => (g.choices ? { id: g.id, choices: g.choices } : { id: g.id })),
    },
    key: { kind: "GAP", answers: Object.fromEntries(gaps.map((g) => [g.id, g.answers])) },
    explanation,
  };
}

const A1: SeedItem[] = [
  choice("A1", "praesens", "EASY", "Ich ___ aus der Türkei.", ["bin", "bist", "ist", "sind"], "a",
    "Zu \"ich\" gehört die Form \"bin\" von sein."),
  choice("A1", "artikel", "EASY", "___ Buch liegt auf dem Tisch.", ["Der", "Das", "Die", "Den"], "b",
    "\"Buch\" ist neutral, im Nominativ also \"das\"."),
  choice("A1", "wfrage", "EASY", "___ wohnst du? In Hamburg.", ["Wer", "Was", "Wo", "Wann"], "c",
    "Nach dem Wohnort fragt man mit \"wo\"."),
  choice("A1", "artikel", "MID", "Hast du ___ Bruder?", ["eine", "einen", "ein", "einem"], "b",
    "\"haben\" verlangt den Akkusativ, maskulin: \"einen\"."),
  choice("A1", "praesens", "MID", "Wir ___ heute keine Zeit.", ["hat", "habt", "haben", "hast"], "c",
    "Zu \"wir\" gehört die Form \"haben\"."),
  choice("A1", "plural", "MID", "Im Zimmer stehen zwei ___.", ["Tisch", "Tischen", "Tischer", "Tische"], "d",
    "Der Plural von \"der Tisch\" ist \"die Tische\"."),
  choice("A1", "praesens", "HARD", "Mein Bruder ___ gern Pizza.", ["isst", "esst", "essen", "iss"], "a",
    "\"essen\" hat in der 3. Person Singular den Vokalwechsel e zu i: \"er isst\"."),
  choice("A1", "negation", "HARD", "Ich trinke ___ Kaffee, ich trinke Tee.", ["nicht", "keine", "kein", "keinen"], "d",
    "Nomen ohne Artikel werden mit \"kein\" verneint, \"Kaffee\" ist maskulin im Akkusativ: \"keinen\"."),
  gap("A1", "pronomen", "EASY", "Das ist Anna. {{g1}} kommt aus Wien.",
    [{ id: "g1", choices: ["Er", "Sie", "Es", "Ihr"], answers: ["Sie"] }],
    "Anna ist eine Frau, das Personalpronomen ist \"sie\"."),
  gap("A1", "praesens", "EASY", "Wie alt {{g1}} du? Ich {{g2}} 25 Jahre alt.",
    [{ id: "g1", answers: ["bist"] }, { id: "g2", answers: ["bin"] }],
    "sein: \"du bist\", \"ich bin\"."),
  gap("A1", "praesens", "MID", "Meine Eltern {{g1}} in Berlin.",
    [{ id: "g1", choices: ["wohnt", "wohnen", "wohnst", "wohne"], answers: ["wohnen"] }],
    "\"Meine Eltern\" ist Plural (sie), also \"wohnen\"."),
  gap("A1", "plural", "HARD", "Ich habe zwei {{g1}}: einen Sohn und eine Tochter.",
    [{ id: "g1", choices: ["Kind", "Kinder", "Kindern", "Kinds"], answers: ["Kinder"] }],
    "Der Plural von \"das Kind\" ist \"die Kinder\"."),
  gap("A1", "wfrage", "HARD", "{{g1}} kommst du? Aus Spanien.",
    [{ id: "g1", answers: ["Woher", "woher"] }],
    "Nach der Herkunft fragt man mit \"woher\"."),
];

const A2: SeedItem[] = [
  choice("A2", "perfekt", "EASY", "Gestern ___ ich ins Kino gegangen.", ["habe", "bin", "war", "hatte"], "b",
    "\"gehen\" ist ein Verb der Bewegung und bildet das Perfekt mit \"sein\"."),
  choice("A2", "dativ", "HARD", "Ich helfe ___ Mutter in der Küche.", ["meiner", "meine", "mein", "meinen"], "a",
    "\"helfen\" verlangt den Dativ, feminin: \"meiner\"."),
  choice("A2", "modalverb", "EASY", "Hier ist Rauchen verboten. Du ___ hier nicht rauchen.", ["dürfst", "darf", "darfst", "dürft"], "c",
    "\"dürfen\" in der 2. Person Singular lautet \"du darfst\"."),
  choice("A2", "trennbar", "MID", "Wann ___ der Zug in München an?", ["ankommt", "kommen", "kommt", "angekommen"], "c",
    "Bei trennbaren Verben steht der Verbstamm an Position 2, das Präfix \"an\" am Satzende."),
  choice("A2", "komparativ", "MID", "Mein Bruder ist zwei Jahre älter und auch ___ als ich.", ["großer", "am größten", "groß", "größer"], "d",
    "Beim Vergleich mit \"als\" steht der Komparativ, bei \"groß\" mit Umlaut: \"größer\"."),
  choice("A2", "praeposition", "HARD", "Das Handy liegt ___ Tisch.", ["auf dem", "auf den", "auf der", "auf das"], "a",
    "Wechselpräposition mit \"liegen\" (Wo?) verlangt den Dativ: \"auf dem Tisch\"."),
  choice("A2", "perfekt", "MID", "Wir haben den Film schon ___.", ["gesieht", "geseht", "sahen", "gesehen"], "d",
    "\"sehen\" ist unregelmäßig, das Partizip II lautet \"gesehen\"."),
  choice("A2", "praeposition", "HARD", "Ich stecke das Handy ___ Tasche.", ["in der", "in die", "in den", "im"], "b",
    "Wechselpräposition mit Richtung (Wohin?) verlangt den Akkusativ: \"in die Tasche\"."),
  gap("A2", "modalverb", "EASY", "Ich {{g1}} heute leider nicht kommen, ich bin krank. (können)",
    [{ id: "g1", answers: ["kann"] }],
    "\"können\" in der 1. Person Singular lautet \"ich kann\"."),
  gap("A2", "dativ", "EASY", "Wir fahren mit {{g1}} Bus zur Arbeit.",
    [{ id: "g1", choices: ["der", "dem", "den", "des"], answers: ["dem"] }],
    "\"mit\" steht immer mit Dativ, maskulin: \"mit dem Bus\"."),
  gap("A2", "trennbar", "MID", "Ich {{g1}} morgen um 6 Uhr {{g2}}. (aufstehen)",
    [{ id: "g1", answers: ["stehe"] }, { id: "g2", answers: ["auf"] }],
    "Das trennbare Präfix \"auf\" steht am Satzende: \"Ich stehe ... auf.\""),
  gap("A2", "komparativ", "MID", "Im Sommer ist es hier viel {{g1}} als im Winter.",
    [{ id: "g1", choices: ["warm", "wärmer", "am wärmsten", "wärmste"], answers: ["wärmer"] }],
    "Vergleich mit \"als\" verlangt den Komparativ \"wärmer\"."),
  gap("A2", "perfekt", "HARD", "Letztes Jahr {{g1}} wir nach Italien {{g2}}.",
    [
      { id: "g1", choices: ["haben", "sind", "hat"], answers: ["sind"] },
      { id: "g2", choices: ["gefahren", "gefahrt", "fahren"], answers: ["gefahren"] },
    ],
    "\"fahren\" bildet das Perfekt mit \"sein\", Partizip II: \"gefahren\"."),
];

const B1: SeedItem[] = [
  choice("B1", "nebensatz", "EASY", "Ich bleibe heute zu Hause, ___ ich krank bin.", ["denn", "weil", "deshalb", "trotzdem"], "b",
    "Das Verb steht am Satzende, also braucht es die Subjunktion \"weil\"."),
  choice("B1", "nebensatz", "EASY", "Ich weiß, ___ er morgen kommt.", ["das", "was", "damit", "dass"], "d",
    "Ein Inhaltssatz nach \"wissen\" wird mit der Konjunktion \"dass\" eingeleitet."),
  choice("B1", "relativsatz", "HARD", "Das ist der Mann, ___ ich gestern geholfen habe.", ["den", "der", "dem", "dessen"], "c",
    "\"helfen\" verlangt den Dativ, maskulines Relativpronomen im Dativ: \"dem\"."),
  choice("B1", "praeteritum", "MID", "Als Kind ___ ich jeden Sommer bei meiner Oma.", ["war", "bin", "wäre", "sei"], "a",
    "Vergangenes wird mit \"als\" im Präteritum erzählt: \"ich war\"."),
  choice("B1", "konjunktiv2", "MID", "Wenn ich mehr Geld hätte, ___ ich eine Weltreise machen.", ["werde", "würde", "wurde", "wird"], "b",
    "Irreale Bedingung: Hauptsatz mit Konjunktiv II \"würde\" + Infinitiv."),
  choice("B1", "passiv", "MID", "Das Auto ___ jeden Samstag gewaschen.", ["werden", "hat", "wird", "worden"], "c",
    "Passiv Präsens: \"werden\" (3. Person Singular \"wird\") + Partizip II."),
  choice("B1", "adjektiv", "MID", "Sie trägt heute ein ___ Kleid.", ["rote", "roten", "roter", "rotes"], "d",
    "Nach unbestimmtem Artikel \"ein\" im Neutrum Akkusativ endet das Adjektiv auf \"-es\"."),
  choice("B1", "konnektor", "HARD", "___ er sehr müde war, arbeitete er noch bis Mitternacht.", ["Obwohl", "Weil", "Trotzdem", "Dass"], "a",
    "Ein Gegensatz im Nebensatz mit Verb am Ende wird mit \"obwohl\" ausgedrückt."),
  gap("B1", "nebensatz", "EASY", "Ich hoffe, {{g1}} du bald wieder gesund bist.",
    [{ id: "g1", answers: ["dass", "daß"] }],
    "Nach \"hoffen\" folgt ein Inhaltssatz mit \"dass\"."),
  gap("B1", "relativsatz", "EASY", "Die Frau, {{g1}} neben mir wohnt, ist Ärztin.",
    [{ id: "g1", choices: ["die", "der", "deren", "denen"], answers: ["die"] }],
    "Das Relativpronomen ist Subjekt (Nominativ) und feminin: \"die\"."),
  gap("B1", "praeteritum", "MID", "Früher {{g1}} wir kein Auto. (haben)",
    [{ id: "g1", answers: ["hatten"] }],
    "Präteritum von \"haben\" in der 1. Person Plural: \"wir hatten\"."),
  gap("B1", "adjektiv", "HARD", "Ich möchte einen {{g1}} Kaffee und ein {{g2}} Stück Kuchen.",
    [
      { id: "g1", choices: ["heiß", "heißen", "heißer", "heißes"], answers: ["heißen"] },
      { id: "g2", choices: ["klein", "kleines", "kleinen", "kleiner"], answers: ["kleines"] },
    ],
    "Maskulin Akkusativ nach \"einen\": \"-en\"; Neutrum Akkusativ nach \"ein\": \"-es\"."),
  gap("B1", "passiv", "HARD", "In Deutschland {{g1}} viel Brot {{g2}}. (essen, Passiv Präsens)",
    [{ id: "g1", answers: ["wird"] }, { id: "g2", answers: ["gegessen"] }],
    "Passiv Präsens: \"wird\" + Partizip II \"gegessen\" am Satzende."),
];

const B2: SeedItem[] = [
  choice("B2", "passiv", "EASY", "Die Brücke muss dringend ___.", ["repariert worden", "repariert wird", "reparieren werden", "repariert werden"], "d",
    "Passiv mit Modalverb: Modalverb + Partizip II + \"werden\"."),
  choice("B2", "konjunktiv2", "EASY", "Wenn ich das gewusst ___, wäre ich früher gekommen.", ["habe", "hatte", "hätte", "würde"], "c",
    "Irreale Bedingung in der Vergangenheit: \"hätte\" + Partizip II."),
  choice("B2", "plusquamperfekt", "MID", "Nachdem wir gegessen ___, gingen wir ins Theater.", ["haben", "hatten", "hätten", "sind"], "b",
    "Vorzeitigkeit zum Präteritum wird mit dem Plusquamperfekt ausgedrückt: \"hatten gegessen\"."),
  choice("B2", "konnektor", "MID", "Die Wohnung ist ideal: Sie ist ___ hell ___ ruhig, und die Miete ist günstig.", ["weder ... noch", "sowohl ... als auch", "je ... desto", "entweder ... oder"], "b",
    "Beide positiven Eigenschaften treffen zu, also \"sowohl ... als auch\"."),
  choice("B2", "nominalisierung", "MID", "Weil es stark regnete, fiel das Spiel aus. = ___ des starken Regens fiel das Spiel aus.", ["Wegen", "Trotz", "Obwohl", "Statt"], "a",
    "Der kausale Nebensatz mit \"weil\" wird zur Präposition \"wegen\" + Genitiv nominalisiert."),
  choice("B2", "partizip", "HARD", "Die ___ Fenster müssen ersetzt werden.", ["zerbrach", "zerbrochene", "zerbrochenen", "zerbrochen"], "c",
    "Partizip II als Attribut nach bestimmtem Artikel im Plural endet auf \"-en\"."),
  choice("B2", "konjunktiv2", "MID", "Hättest du mich angerufen, ___ ich dich vom Bahnhof abgeholt.", ["würde", "wäre", "habe", "hätte"], "d",
    "Konjunktiv II der Vergangenheit: \"hätte\" + Partizip II \"abgeholt\"."),
  choice("B2", "passiv", "HARD", "Der Vertrag hätte schon gestern unterschrieben ___ müssen.", ["werden", "worden", "wurden", "sein"], "a",
    "Passiv mit Modalverb im Konjunktiv II der Vergangenheit: \"hätte ... unterschrieben werden müssen\"."),
  gap("B2", "plusquamperfekt", "EASY", "Nachdem er das Studium {{g1}} hatte, zog er nach Hamburg.",
    [{ id: "g1", choices: ["beendet", "beenden", "beendete"], answers: ["beendet"] }],
    "Plusquamperfekt: \"hatte\" + Partizip II \"beendet\"."),
  gap("B2", "konnektor", "EASY", "Je mehr man übt, {{g1}} besser spricht man.",
    [{ id: "g1", answers: ["desto", "umso", "um so"] }],
    "Der zweiteilige Konnektor lautet \"je ... desto\" bzw. \"je ... umso\"."),
  gap("B2", "passiv", "MID", "Das Problem konnte leider nicht rechtzeitig {{g1}} {{g2}}. (lösen, Passiv)",
    [{ id: "g1", answers: ["gelöst"] }, { id: "g2", answers: ["werden"] }],
    "Passiv mit Modalverb: \"konnte ... gelöst werden\"."),
  gap("B2", "nominalisierung", "HARD", "Die {{g1}} (bearbeiten) des Antrags dauert etwa zwei Wochen.",
    [{ id: "g1", answers: ["Bearbeitung", "bearbeitung"] }],
    "Das Verb \"bearbeiten\" wird mit dem Suffix \"-ung\" nominalisiert: \"die Bearbeitung\"."),
  gap("B2", "konjunktiv2", "HARD", "Ohne deine Hilfe {{g1}} ich die Prüfung letztes Jahr nicht {{g2}}.",
    [
      { id: "g1", choices: ["hätte", "hatte", "wäre", "habe"], answers: ["hätte"] },
      { id: "g2", choices: ["bestanden", "bestehen", "bestand"], answers: ["bestanden"] },
    ],
    "Irrealer Sachverhalt in der Vergangenheit: \"hätte ... bestanden\"."),
];

const C1: SeedItem[] = [
  choice("C1", "konjunktiv1", "EASY", "(Zeitungsbericht) Der Minister erklärte, er ___ von den Plänen nichts gewusst.", ["hatte", "habe", "hat", "haben"], "b",
    "Indirekte Rede im Pressestil steht im Konjunktiv I: \"er habe gewusst\"."),
  choice("C1", "konjunktiv1", "MID", "Die Sprecherin betonte, das Unternehmen ___ keine Stellen abbauen.", ["wird", "würden", "worden", "werde"], "d",
    "Konjunktiv I von \"werden\" in der 3. Person Singular: \"werde\"."),
  choice("C1", "partizip", "MID", "Die ___ Maßnahmen zeigen bereits Wirkung.", ["von der Regierung im letzten Jahr eingeführten", "von der Regierung im letzten Jahr eingeführte", "im letzten Jahr von der Regierung einführenden", "von der Regierung eingeführt im letzten Jahr"], "a",
    "Erweitertes Partizipialattribut: Ergänzungen vor dem Partizip II, Endung \"-en\" nach \"die\" im Plural."),
  choice("C1", "funktionsverb", "EASY", "Das neue Gesetz tritt am 1. Januar in ___.", ["Gang", "Betrieb", "Kraft", "Frage"], "c",
    "Das Funktionsverbgefüge lautet \"in Kraft treten\"."),
  choice("C1", "funktionsverb", "MID", "Wir müssen diese Faktoren bei der Planung in Betracht ___.", ["nehmen", "ziehen", "stellen", "bringen"], "b",
    "Die feste Verbindung lautet \"in Betracht ziehen\"."),
  choice("C1", "praeposition", "HARD", "___ der heftigen Kritik hielt die Regierung an ihrem Kurs fest.", ["Infolge", "Anlässlich", "Ungeachtet", "Zwecks"], "c",
    "\"ungeachtet\" + Genitiv drückt einen Gegensatz aus (trotz der Kritik)."),
  choice("C1", "konnektor", "MID", "Die Studie ist methodisch solide; ___ bleiben einige Fragen offen.", ["folglich", "somit", "demnach", "gleichwohl"], "d",
    "\"gleichwohl\" ist konzessiv (dennoch), die anderen Adverbien sind konsekutiv."),
  choice("C1", "konnektor", "HARD", "Er hat die Stelle nicht bekommen, ___ er hervorragend qualifiziert war.", ["wenngleich", "sofern", "zumal", "indem"], "a",
    "\"wenngleich\" leitet einen konzessiven Nebensatz ein (obwohl)."),
  gap("C1", "konjunktiv1", "EASY", "Der Zeuge gab an, er {{g1}} den Täter nicht gesehen.",
    [{ id: "g1", choices: ["habe", "hat", "hatte", "haben"], answers: ["habe"] }],
    "Indirekte Rede: Konjunktiv I \"er habe gesehen\"."),
  gap("C1", "praeposition", "EASY", "Das Projekt wurde {{g1}} fehlender Finanzierung eingestellt.",
    [{ id: "g1", choices: ["aufgrund", "trotz", "anstatt", "zwecks"], answers: ["aufgrund"] }],
    "Der Grund wird mit \"aufgrund\" + Genitiv angegeben."),
  gap("C1", "nomenverb", "MID", "Unser Chef hat schon immer großen Wert {{g1}} Pünktlichkeit {{g2}}.",
    [
      { id: "g1", choices: ["auf", "an", "für", "über"], answers: ["auf"] },
      { id: "g2", choices: ["gelegt", "gestellt", "gesetzt", "genommen"], answers: ["gelegt"] },
    ],
    "Die Nomen-Verb-Verbindung lautet \"Wert auf etwas legen\"."),
  gap("C1", "funktionsverb", "HARD", "Die Ergebnisse müssen noch einer genauen Prüfung {{g1}} werden.",
    [{ id: "g1", answers: ["unterzogen", "unterworfen"] }],
    "Das Funktionsverbgefüge lautet \"einer Prüfung unterziehen\", im Passiv \"unterzogen werden\"."),
  gap("C1", "partizip", "HARD", "Der Bericht, der gestern veröffentlicht wurde, sorgt für Aufregung. = Der gestern {{g1}} Bericht sorgt für Aufregung.",
    [{ id: "g1", answers: ["veröffentlichte", "veroeffentlichte"] }],
    "Der Relativsatz wird zum Partizipialattribut: Partizip II mit Endung \"-e\" nach \"der\"."),
];

const C2: SeedItem[] = [
  choice("C2", "idiomatik", "EASY", "Mit diesem Argument hat sie den Nagel auf den ___ getroffen.", ["Kopf", "Punkt", "Hut", "Tisch"], "a",
    "Die Redewendung lautet \"den Nagel auf den Kopf treffen\"."),
  choice("C2", "idiomatik", "MID", "Deine Ausreden kannst du dir ___ die Haare schmieren.", ["auf", "an", "unter", "in"], "d",
    "Die Wendung lautet \"sich etwas in die Haare schmieren können\" (etwas ist wertlos)."),
  choice("C2", "praeposition", "MID", "___ der Geschäftsleitung wurden keine Einwände erhoben.", ["Seitens", "Mittels", "Anhand", "Kraft"], "a",
    "\"seitens\" + Genitiv nennt die handelnde Seite (von Seiten der Geschäftsleitung)."),
  choice("C2", "modalpartikel", "EASY", "Komm ___ mal her, ich will dir etwas zeigen!", ["denn", "etwa", "doch", "wohl"], "c",
    "In Aufforderungen verstärkt die Modalpartikel \"doch\" die Bitte; \"denn\" und \"etwa\" stehen nur in Fragen."),
  choice("C2", "modalpartikel", "MID", "Hast du ___ vergessen, dass wir heute Abend Gäste haben?", ["halt", "mal", "etwa", "ruhig"], "c",
    "\"etwa\" in Entscheidungsfragen drückt Überraschung oder Vorwurf aus."),
  choice("C2", "register", "EASY", "Welche Formulierung passt in einen formellen Geschäftsbrief?", ["Sorry für den Stress.", "Wir hoffen, das ist okay für Sie.", "Schreiben Sie mal zurück.", "Wir bitten um Ihr Verständnis."], "d",
    "Nur \"Wir bitten um Ihr Verständnis\" entspricht dem formellen Register."),
  choice("C2", "idiomatik", "HARD", "Die groß angekündigte Kampagne war ein Schlag ins ___: Kaum jemand nahm Notiz davon.", ["Gesicht", "Wasser", "Herz", "Blaue"], "b",
    "\"ein Schlag ins Wasser\" bedeutet einen Misserfolg; \"Schlag ins Gesicht\" wäre eine Kränkung."),
  choice("C2", "register", "HARD", "Welcher Satz gehört am ehesten zur gehobenen Schriftsprache?", ["Er hat sich darüber total aufgeregt.", "Er zeigte sich darüber äußerst befremdet.", "Das hat ihn voll genervt.", "Er war deswegen ziemlich sauer."], "b",
    "\"sich befremdet zeigen\" ist gehoben, die anderen Sätze sind umgangssprachlich."),
  gap("C2", "modalpartikel", "EASY", "Nun beruhige dich, das ist {{g1}} nicht so schlimm!",
    [{ id: "g1", choices: ["doch", "etwa", "denn", "bloß"], answers: ["doch"] }],
    "\"doch\" im Aussagesatz beschwichtigt und verweist auf Bekanntes; \"etwa\" und \"denn\" gehören in Fragen."),
  gap("C2", "praeposition", "MID", "{{g1}} der angespannten Haushaltslage müssen alle Ressorts sparen.",
    [{ id: "g1", choices: ["Angesichts", "Anhand", "Zugunsten", "Entgegen"], answers: ["Angesichts"] }],
    "\"angesichts\" + Genitiv nennt den Umstand, der die Folge begründet."),
  gap("C2", "idiomatik", "MID", "Sie hat die Prüfung nur mit Ach und {{g1}} bestanden.",
    [{ id: "g1", answers: ["Krach", "krach"] }],
    "Die Zwillingsformel lautet \"mit Ach und Krach\" (nur mit Mühe)."),
  gap("C2", "idiomatik", "HARD", "Endlich hat ihm jemand reinen {{g1}} eingeschenkt und ihm die Wahrheit gesagt.",
    [{ id: "g1", answers: ["Wein", "wein"] }],
    "Die Redewendung lautet \"jemandem reinen Wein einschenken\"."),
  gap("C2", "stil", "HARD", "Die Kosten werden nach {{g1}} der gesetzlichen Bestimmungen erstattet.",
    [{ id: "g1", choices: ["Maßgabe", "Hinsicht", "Anbetracht", "Belieben"], answers: ["Maßgabe"] }],
    "Die amtssprachliche Wendung lautet \"nach Maßgabe\" + Genitiv (entsprechend)."),
];

export const grammar: SeedBankPart = {
  stimuli: [],
  items: [...A1, ...A2, ...B1, ...B2, ...C1, ...C2],
};
