import type { TfngValue } from "@/lib/exam/types";
import type { SeedBankPart, SeedItem, SeedStimulus } from "./types";

/**
 * Starter listening clips, three per CEFR level with three items each.
 *
 * Every body is a TTS script: one turn per line as `Label: text`, and every
 * label is declared in `speakers`. At most two voices per clip. Numbers are
 * written the way they are spoken wherever a digit would be ambiguous.
 *
 * `choice` takes the correct option first and places it at `pos`, so the key
 * positions are set explicitly and spread across a, b, c and d.
 */

type Level = SeedItem["level"];
type Within = NonNullable<SeedItem["within"]>;
type Skill = "gist" | "detail" | "attitude" | "inference";

const IDS = ["a", "b", "c", "d"] as const;

function clip(
  key: string,
  level: Level,
  title: string,
  topic: string,
  speakers: Array<{ label: string; voice: "A" | "B" }>,
  lines: string[],
): SeedStimulus {
  return { key, section: "LISTENING", level, title, topic, speakers, body: lines.join("\n") };
}

function choice(
  level: Level,
  stimulusKey: string,
  skill: Skill,
  within: Within,
  prompt: string,
  correct: string,
  distractors: string[],
  pos: number,
  explanation: string,
): SeedItem {
  const texts = [...distractors];
  texts.splice(pos, 0, correct);
  return {
    section: "LISTENING",
    level,
    type: "SINGLE_CHOICE",
    skillTag: `listening.${skill}`,
    within,
    stimulusKey,
    prompt,
    content: { kind: "CHOICE", options: texts.map((text, i) => ({ id: IDS[i], text })) },
    key: { kind: "CHOICE", correct: [IDS[pos]] },
    explanation,
  };
}

function tfng(
  level: Level,
  stimulusKey: string,
  skill: Skill,
  within: Within,
  statements: Array<[string, TfngValue]>,
  explanation: string,
): SeedItem {
  const ids = statements.map((_, i) => `s${i + 1}`);
  return {
    section: "LISTENING",
    level,
    type: "TRUE_FALSE_NG",
    skillTag: `listening.${skill}`,
    within,
    stimulusKey,
    prompt: "Richtig, falsch oder nicht im Text? Entscheiden Sie für jede Aussage.",
    content: { kind: "TFNG", statements: statements.map(([text], i) => ({ id: ids[i], text })) },
    key: { kind: "TFNG", answers: Object.fromEntries(statements.map(([, v], i) => [ids[i], v])) },
    explanation,
  };
}

const stimuli: SeedStimulus[] = [
  // ---------------------------------------------------------------- A1
  clip(
    "l-a1-bahnhof",
    "A1",
    "Durchsage am Bahnhof",
    "Reisen",
    [{ label: "Ansage", voice: "A" }],
    [
      "Ansage: Achtung, eine Information für alle Fahrgäste. Der Zug nach Hamburg fährt heute nicht von Gleis drei. Er fährt von Gleis fünf. Die Abfahrt ist um zehn Uhr fünfzehn. Bitte gehen Sie jetzt zu Gleis fünf. Wir wünschen Ihnen eine gute Reise.",
    ],
  ),
  clip(
    "l-a1-cafe",
    "A1",
    "Im Café",
    "Essen und Trinken",
    [
      { label: "Kellnerin", voice: "A" },
      { label: "Gast", voice: "B" },
    ],
    [
      "Kellnerin: Guten Tag. Was möchten Sie trinken?",
      "Gast: Einen Kaffee, bitte. Und ein Wasser.",
      "Kellnerin: Möchten Sie auch etwas essen?",
      "Gast: Ja, ich nehme ein Stück Apfelkuchen.",
      "Kellnerin: Gern. Das macht zusammen acht Euro fünfzig.",
      "Gast: Hier sind zehn Euro. Das stimmt so.",
      "Kellnerin: Vielen Dank!",
    ],
  ),
  clip(
    "l-a1-party",
    "A1",
    "Nachricht auf der Mailbox",
    "Freizeit",
    [{ label: "Lena", voice: "B" }],
    [
      "Lena: Hallo Tom, hier ist Lena. Ich mache am Samstag eine kleine Party. Sie beginnt um acht Uhr am Abend. Meine Adresse ist Gartenstraße zwölf. Kannst du bitte Musik mitbringen? Ruf mich bitte an. Meine Nummer ist null eins sieben sechs, zwei drei vier fünf. Tschüss!",
    ],
  ),

  // ---------------------------------------------------------------- A2
  clip(
    "l-a2-arzt",
    "A2",
    "Anruf in der Arztpraxis",
    "Gesundheit",
    [
      { label: "Frau Keller", voice: "A" },
      { label: "Herr Demir", voice: "B" },
    ],
    [
      "Frau Keller: Praxis Doktor Brandt, Keller am Apparat, guten Morgen.",
      "Herr Demir: Guten Morgen, mein Name ist Demir. Ich brauche bitte einen Termin. Ich habe seit drei Tagen Halsschmerzen und Fieber.",
      "Frau Keller: Oh, das tut mir leid. Heute ist leider alles voll. Morgen um neun Uhr ist noch etwas frei. Passt Ihnen das?",
      "Herr Demir: Morgen früh muss ich arbeiten. Geht es auch am Nachmittag?",
      "Frau Keller: Ja, um Viertel nach drei.",
      "Herr Demir: Sehr gut, das passt. Muss ich etwas mitbringen?",
      "Frau Keller: Bitte bringen Sie Ihre Versichertenkarte mit. Und kommen Sie zehn Minuten früher.",
      "Herr Demir: Mache ich. Vielen Dank, auf Wiederhören.",
    ],
  ),
  clip(
    "l-a2-wochenende",
    "A2",
    "Wie war dein Wochenende?",
    "Freizeit",
    [
      { label: "Jonas", voice: "B" },
      { label: "Mia", voice: "A" },
    ],
    [
      "Jonas: Hallo Mia! Wie war dein Wochenende?",
      "Mia: Super! Am Samstag war ich mit meiner Schwester in Köln. Wir haben den Dom besichtigt und sind am Rhein spazieren gegangen.",
      "Jonas: Toll! Und wie seid ihr hingefahren?",
      "Mia: Mit dem Zug. Die Fahrt hat nur eine Stunde gedauert. Und du? Was hast du gemacht?",
      "Jonas: Leider nicht viel. Ich war erkältet und bin zu Hause geblieben. Am Sonntag habe ich einen Film gesehen und viel Tee getrunken.",
      "Mia: Oh nein! Geht es dir jetzt besser?",
      "Jonas: Ja, heute geht es schon wieder.",
    ],
  ),
  clip(
    "l-a2-supermarkt",
    "A2",
    "Durchsage im Supermarkt",
    "Einkaufen",
    [{ label: "Ansage", voice: "B" }],
    [
      "Ansage: Liebe Kundinnen und Kunden, herzlich willkommen im Frischmarkt. Heute haben wir tolle Angebote für Sie. Ein Kilo Tomaten kostet nur einen Euro neunundneunzig. Und in unserer Bäckerei gibt es alle Brötchen zum halben Preis, aber nur bis zwölf Uhr. Außerdem eine wichtige Information: Ab nächster Woche haben wir länger geöffnet, von Montag bis Samstag bis zweiundzwanzig Uhr. Am Sonntag bleibt der Markt wie immer geschlossen. Vielen Dank für Ihren Einkauf und einen schönen Tag!",
    ],
  ),

  // ---------------------------------------------------------------- B1
  clip(
    "l-b1-wohnung",
    "B1",
    "Anruf wegen einer Wohnung",
    "Wohnen",
    [
      { label: "Frau Lorenz", voice: "A" },
      { label: "Sara", voice: "B" },
    ],
    [
      "Frau Lorenz: Lorenz, guten Tag.",
      "Sara: Guten Tag, Frau Lorenz. Hier spricht Sara Nowak. Ich rufe wegen der Wohnung in der Lindenstraße an. Ist sie noch frei?",
      "Frau Lorenz: Ja, die ist noch frei. Es sind zwei Zimmer, eine Küche und ein Bad, insgesamt fünfundfünfzig Quadratmeter.",
      "Sara: Und wie hoch ist die Miete?",
      "Frau Lorenz: Die Kaltmiete beträgt sechshundertfünfzig Euro. Dazu kommen ungefähr hundertzwanzig Euro Nebenkosten.",
      "Sara: Gibt es einen Balkon?",
      "Frau Lorenz: Nein, leider nicht. Aber die Mieter dürfen den Garten hinter dem Haus benutzen.",
      "Sara: Das klingt schön. Darf man Haustiere haben? Ich habe nämlich eine Katze.",
      "Frau Lorenz: Eine Katze ist kein Problem. Hunde möchten wir im Haus allerdings nicht.",
      "Sara: Wann könnte ich mir die Wohnung ansehen?",
      "Frau Lorenz: Am Donnerstag um halb sechs zeige ich sie mehreren Interessenten. Kommen Sie doch einfach dazu.",
      "Sara: Sehr gern. Dann bis Donnerstag, und vielen Dank.",
    ],
  ),
  clip(
    "l-b1-wochenendtipps",
    "B1",
    "Tipps fürs Wochenende",
    "Freizeit und Kultur",
    [{ label: "Moderatorin", voice: "A" }],
    [
      "Moderatorin: Und hier unsere Tipps fürs Wochenende. Am Samstag beginnt auf dem Marktplatz das Stadtfest. Von elf Uhr morgens bis Mitternacht gibt es Livemusik, Essensstände aus zwölf Ländern und ein großes Programm für Kinder. Der Eintritt ist frei.",
      "Moderatorin: Wer mit dem Auto kommen möchte, sollte wissen: Die Innenstadt ist ab Freitagabend für den Verkehr gesperrt. Nehmen Sie also lieber Bus oder Bahn. Die fahren am Wochenende sogar alle zehn Minuten.",
      "Moderatorin: Für alle, die es ruhiger mögen: Im Stadtmuseum eröffnet am Sonntag eine Ausstellung über die Geschichte der Fahrradproduktion in unserer Region. Die Führung um vierzehn Uhr ist kostenlos. Eine Anmeldung ist aber nötig, weil nur zwanzig Personen teilnehmen können.",
      "Moderatorin: Und das Wetter spielt auch mit: Es bleibt trocken, bei bis zu vierundzwanzig Grad.",
    ],
  ),
  clip(
    "l-b1-abschied",
    "B1",
    "Ein Abschiedsfest planen",
    "Arbeit",
    [
      { label: "Daniel", voice: "B" },
      { label: "Petra", voice: "A" },
    ],
    [
      "Daniel: Petra, hast du kurz Zeit? Es geht um das Abschiedsfest für Herrn Schulte.",
      "Petra: Klar. Er geht ja Ende des Monats in Rente, oder?",
      "Daniel: Genau. Ich dachte an Freitag, den achtundzwanzigsten, nach der Arbeit. Vielleicht in der Kantine?",
      "Petra: Die Kantine finde ich ein bisschen langweilig. Das Restaurant am See hat einen großen Raum, den man mieten kann.",
      "Daniel: Das wäre sicher schöner, aber auch teurer. Wir haben nur das Geld aus der Sammlung, knapp dreihundert Euro.",
      "Petra: Stimmt. Was hältst du davon: Wir feiern in der Kantine, aber jeder bringt etwas zu essen mit. Dann bleibt genug Geld für ein richtig gutes Geschenk.",
      "Daniel: Gute Idee. Er hat doch erzählt, dass er mit seiner Frau eine Radtour an der Donau machen will. Vielleicht ein Gutschein für ein Hotel unterwegs?",
      "Petra: Perfekt. Ich kümmere mich um den Gutschein, und du schreibst die Einladung an alle.",
      "Daniel: Abgemacht.",
    ],
  ),

  // ---------------------------------------------------------------- B2
  clip(
    "l-b2-homeoffice",
    "B2",
    "Interview: Zurück ins Büro?",
    "Arbeitswelt",
    [
      { label: "Moderator", voice: "B" },
      { label: "Frau Albers", voice: "A" },
    ],
    [
      "Moderator: Frau Albers, viele Firmen holen ihre Beschäftigten gerade zurück ins Büro. Ist das Homeoffice schon wieder vorbei?",
      "Frau Albers: Vorbei würde ich nicht sagen. Aber die anfängliche Begeisterung ist einer realistischeren Sicht gewichen. Man hat gemerkt, dass konzentriertes Arbeiten zu Hause oft sehr gut funktioniert. Was dagegen leidet, sind die spontanen Gespräche, also der kurze Austausch in der Kaffeeküche, aus dem manchmal die besten Ideen entstehen.",
      "Moderator: Das heißt, die Unternehmen haben recht, wenn sie mehr Präsenz verlangen?",
      "Frau Albers: Teilweise. Problematisch finde ich es, wenn Präsenz zur Kontrolle eingefordert wird. Wer seinen Leuten nicht vertraut, löst das Problem nicht, indem er sie an den Schreibtisch holt. Sinnvoll ist es, gemeinsam festzulegen, wofür man sich trifft. Viele Teams kommen inzwischen zwei Tage pro Woche zusammen, und zwar gezielt für Besprechungen, Workshops oder die Einarbeitung neuer Kolleginnen und Kollegen.",
      "Moderator: Und die übrigen Tage?",
      "Frau Albers: Da darf jeder selbst entscheiden. Wichtig ist allerdings, dass man auch zu Hause klare Grenzen zieht. In unseren Befragungen gibt fast die Hälfte an, abends noch dienstliche E-Mails zu lesen. Auf Dauer ist das ein echtes Gesundheitsrisiko.",
    ],
  ),
  clip(
    "l-b2-altstadt",
    "B2",
    "Bürgerversammlung: Autofreie Altstadt",
    "Stadt und Verkehr",
    [
      { label: "Herr Roth", voice: "B" },
      { label: "Frau Heinemann", voice: "A" },
    ],
    [
      "Herr Roth: Ab dem nächsten Frühjahr soll die Altstadt für private Autos gesperrt werden, zunächst als Versuch für ein Jahr. Lieferverkehr ist morgens bis zehn Uhr weiterhin erlaubt, und Anwohner erhalten eine Sondergenehmigung. Wir erwarten weniger Lärm, bessere Luft und mehr Platz für Menschen statt für Parkplätze.",
      "Frau Heinemann: Ich verstehe die Idee, und ehrlich gesagt gefällt mir die Vorstellung einer ruhigeren Altstadt. Aber als Inhaberin eines Schuhgeschäfts mache ich mir Sorgen. Viele meiner Kundinnen kommen aus den umliegenden Dörfern, und dort fährt der Bus nur einmal pro Stunde. Wenn diese Leute nicht mehr parken können, fahren sie ins Einkaufszentrum vor der Stadt.",
      "Herr Roth: Diese Sorge nehmen wir ernst. Deshalb bauen wir am Stadtrand zwei Parkplätze mit insgesamt vierhundert Stellplätzen. Von dort fährt alle zehn Minuten ein kostenloser Shuttlebus ins Zentrum. Außerdem zeigen Erfahrungen aus anderen Städten, dass Fußgänger im Durchschnitt häufiger in Geschäfte gehen als Autofahrer.",
      "Frau Heinemann: Das mag in Großstädten stimmen. Ich wünsche mir jedenfalls, dass die Händler schon nach sechs Monaten gefragt werden, wie es läuft, und nicht erst am Ende.",
      "Herr Roth: Das halte ich für einen fairen Vorschlag. Wir planen eine Zwischenbilanz im Herbst ein.",
    ],
  ),
  clip(
    "l-b2-roman",
    "B2",
    "Buchkritik im Radio",
    "Literatur",
    [{ label: "Kritikerin", voice: "A" }],
    [
      "Kritikerin: Mit ihrem Roman Das Haus am Kanal legt die Hamburger Autorin Jana Wolff ihr zweites Buch vor, und die Erwartungen waren hoch. Ihr Debüt vor drei Jahren war ein Überraschungserfolg und wurde in zwölf Sprachen übersetzt.",
      "Kritikerin: Auch diesmal erzählt sie eine Familiengeschichte. Drei Geschwister treffen sich nach dem Tod ihrer Mutter im Elternhaus, um es auszuräumen, und dabei kommen alte Konflikte ans Licht. Die älteste Schwester, eine erfolgreiche Anwältin aus München, will das Haus möglichst schnell verkaufen. Der jüngere Bruder dagegen möchte darin wohnen bleiben, und zwischen den beiden steht die mittlere Schwester, die es allen recht machen will.",
      "Kritikerin: Die ersten hundert Seiten sind großartig. Wolff hat ein feines Gespür für Dialoge, und man glaubt jeder Figur jedes Wort. Im Mittelteil verliert das Buch dann leider an Tempo. Es gibt zu viele Rückblenden, und manche Nebenfiguren tauchen auf, ohne dass klar wird, warum. Erst im letzten Drittel findet die Autorin zu ihrer alten Stärke zurück, und das Ende hat mich wirklich berührt.",
      "Kritikerin: Mein Fazit: kein perfektes Buch, aber ein lesenswertes. Wer Geduld mitbringt, wird belohnt. Wer das Debüt geliebt hat, sollte allerdings nicht dasselbe erwarten.",
    ],
  ),

  // ---------------------------------------------------------------- C1
  clip(
    "l-c1-vorlesung",
    "C1",
    "Vorlesung: Warum wir falsch lernen",
    "Wissenschaft und Lernen",
    [{ label: "Professorin", voice: "A" }],
    [
      "Professorin: Meine Damen und Herren, in der letzten Sitzung haben wir über den sogenannten Testeffekt gesprochen. Heute möchte ich eine Frage aufgreifen, die viele von Ihnen im Anschluss gestellt haben: Warum lernen so viele Menschen trotzdem mit Methoden, die nachweislich wenig bringen?",
      "Professorin: Denken Sie an das wiederholte Durchlesen eines Textes oder an das farbige Markieren. Beides fühlt sich produktiv an. Man erkennt den Stoff wieder, und dieses Gefühl der Vertrautheit verwechseln wir mit Wissen. Wer sich dagegen selbst abfragt, stößt ständig auf Lücken. Das ist unangenehm, und genau deshalb halten viele Lernende diese Methode für weniger wirksam, obwohl das Gegenteil der Fall ist.",
      "Professorin: In einer Studie sollten Studierende einen Text entweder viermal lesen oder einmal lesen und dreimal frei wiedergeben. Unmittelbar danach schnitt die erste Gruppe etwas besser ab. Eine Woche später hatte sich das Bild jedoch umgekehrt: Die Gruppe, die sich selbst abgefragt hatte, erinnerte deutlich mehr. Aufschlussreich ist auch, wie die Teilnehmenden ihren eigenen Lernerfolg eingeschätzt hatten. Die Vielleser waren sich ihrer Sache wesentlich sicherer.",
      "Professorin: Für die Praxis bedeutet das: Das subjektive Gefühl, etwas gut gelernt zu haben, ist ein schlechter Ratgeber. Ich will damit übrigens nicht sagen, dass Markieren völlig nutzlos ist. Als erster Schritt, um sich in einem Text zu orientieren, kann es durchaus helfen. Es ersetzt nur nicht die mühsamere Arbeit des Abrufens. Mein Rat für Ihre Prüfungsvorbereitung lautet daher: Schließen Sie das Buch und schreiben Sie auf, was Sie noch wissen. Erst danach schauen Sie nach, was gefehlt hat.",
    ],
  ),
  clip(
    "l-c1-land",
    "C1",
    "Interview: Leere Dörfer, volle Städte",
    "Gesellschaft",
    [
      { label: "Moderatorin", voice: "A" },
      { label: "Herr Brenner", voice: "B" },
    ],
    [
      "Moderatorin: Herr Brenner, in den Großstädten fehlen Wohnungen, während in vielen Dörfern Häuser leer stehen. Warum ziehen nicht einfach mehr Menschen aufs Land?",
      "Herr Brenner: Das klingt naheliegend, greift aber zu kurz. Ein leer stehendes Haus allein ist noch kein Angebot. Die Leute fragen: Gibt es eine Schule, einen Arzt, eine vernünftige Internetverbindung? Und wie komme ich ohne zweites Auto zur Arbeit? Solange diese Fragen offen bleiben, nützt auch das günstigste Haus wenig.",
      "Moderatorin: Seit einigen Jahren arbeiten aber viele Menschen von zu Hause aus. Hat das nichts verändert?",
      "Herr Brenner: Doch, aber weniger, als manche Schlagzeilen vermuten ließen. Wir beobachten zwar eine Abwanderung aus den Kernstädten, allerdings vor allem in den sogenannten Speckgürtel, also in Gemeinden, von denen aus man in einer Stunde in der Stadt ist. Das abgelegene Dorf in zwei Stunden Entfernung profitiert davon kaum.",
      "Moderatorin: Was könnten solche Dörfer denn tun?",
      "Herr Brenner: Einige Gemeinden zeigen, dass es geht. Sie bauen alte Gasthöfe zu Arbeitsräumen um, die man tageweise mieten kann, oder organisieren Mitfahrsysteme. Entscheidend ist aber etwas anderes: Neue Bewohner müssen sich willkommen fühlen. Wo Zugezogene nach Jahren noch als die Neuen gelten, ziehen sie oft wieder weg. Das lässt sich nicht mit Fördergeld lösen.",
      "Moderatorin: Das klingt, als seien Sie eher skeptisch.",
      "Herr Brenner: Sagen wir: realistisch. Das Land kann die Wohnungsprobleme der Städte nicht lösen. Aber es kann einen Beitrag leisten, wenn man es nicht nur als billige Ausweichfläche betrachtet.",
    ],
  ),
  clip(
    "l-c1-viertagewoche",
    "C1",
    "Bericht: Bilanz der Viertagewoche",
    "Wirtschaft",
    [{ label: "Reporter", voice: "B" }],
    [
      "Reporter: Ein halbes Jahr lang haben vierzig Betriebe in Norddeutschland die Viertagewoche erprobt, bei vollem Lohn. Nun liegen die Ergebnisse vor, und sie fallen differenzierter aus, als es die Schlagzeilen der letzten Tage nahelegen.",
      "Reporter: Zunächst die gute Nachricht: Die Zahl der Krankheitstage ist in fast allen teilnehmenden Unternehmen gesunken, im Durchschnitt um etwa ein Fünftel. Die Beschäftigten berichten von weniger Stress und mehr Zeit für Familie und Erholung. Die Produktivität blieb nach Angaben der Unternehmen weitgehend stabil, in einigen Büros stieg sie sogar leicht. Dreißig der vierzig Betriebe wollen das Modell beibehalten.",
      "Reporter: Doch es lohnt sich ein Blick auf die übrigen zehn. Darunter sind auffallend viele Handwerksbetriebe und Pflegeeinrichtungen, also Branchen, in denen sich Arbeit nicht einfach verdichten lässt. Eine Pflegekraft kann ihre Patienten nicht schneller versorgen, nur weil ihr ein Tag fehlt. Hier musste zusätzliches Personal eingestellt werden, und das war auf dem leer gefegten Arbeitsmarkt kaum zu finden. Einige Betriebe haben stattdessen ihre Öffnungszeiten verkürzt, was bei der Kundschaft nicht immer gut ankam.",
      "Reporter: Bemerkenswert ist außerdem, wer an dem Versuch überhaupt teilgenommen hat. Es waren Betriebe, die sich freiwillig beworben hatten. Man darf also vermuten, dass dort ohnehin eine besonders experimentierfreudige Unternehmenskultur herrscht. Ob sich die Ergebnisse auf die gesamte Wirtschaft übertragen lassen, ist damit keineswegs ausgemacht.",
      "Reporter: Die Forscher selbst sprechen vorsichtig von einem vielversprechenden Ansatz für bestimmte Branchen. Das ist weniger spektakulär als manche Überschrift, aber vermutlich näher an der Wahrheit.",
    ],
  ),

  // ---------------------------------------------------------------- C2
  clip(
    "l-c2-handschrift",
    "C2",
    "Streitgespräch: Braucht die Schule noch Handschrift?",
    "Bildung",
    [
      { label: "Herr Kranz", voice: "B" },
      { label: "Frau Seidel", voice: "A" },
    ],
    [
      "Herr Kranz: Ich will gar nicht bestreiten, dass Handschrift einen kulturellen Wert hat. Aber wir müssen ehrlich sein: Die Schulzeit ist begrenzt, und jede Stunde, die Kinder mit dem Üben verbundener Buchstaben verbringen, fehlt woanders, etwa beim Programmieren oder beim kritischen Umgang mit Quellen im Netz. Kaum ein Erwachsener schreibt heute noch mehr als einen Einkaufszettel mit der Hand. Die Frage ist also nicht, ob Handschrift schön ist, sondern ob sie den Platz im Stundenplan rechtfertigt, den sie heute einnimmt.",
      "Frau Seidel: Da machen Sie es sich, mit Verlaub, etwas zu einfach. Es geht doch nicht um Schönschrift als Selbstzweck. Mehrere Studien deuten darauf hin, dass Kinder Buchstaben besser erkennen, wenn sie sie selbst geformt und nicht nur getippt haben. Und wer in einer Vorlesung mitschreibt, statt mitzutippen, ist gezwungen, das Gehörte zu verdichten, anstatt es wortwörtlich festzuhalten. Das ist eine Denkleistung.",
      "Herr Kranz: Die Studien, die Sie ansprechen, kenne ich. Sie sind allerdings meist klein, und die Effekte fallen, wenn man genau hinsieht, recht bescheiden aus. Daraus die Pflicht abzuleiten, jahrelang eine bestimmte Schreibschrift zu üben, halte ich für gewagt.",
      "Frau Seidel: Über die Schreibschrift können wir gerne reden. Ob die Buchstaben verbunden sind oder nicht, ist mir tatsächlich ziemlich gleichgültig. Mir geht es darum, dass Kinder flüssig und lesbar von Hand schreiben können, bevor die Tastatur übernimmt. Wer das abschafft, spart vielleicht ein paar Stunden, gibt aber ein Werkzeug des Denkens aus der Hand, und das lässt sich später nur mühsam nachholen.",
      "Herr Kranz: Dann liegen wir vielleicht näher beieinander, als es zunächst aussah. Eine lesbare Handschrift als Grundlage, ja. Aber keine jahrelange Kalligrafie auf Kosten der digitalen Bildung.",
    ],
  ),
  clip(
    "l-c2-langeweile",
    "C2",
    "Radiofeature: Lob der Langeweile",
    "Psychologie",
    [{ label: "Sprecherin", voice: "A" }],
    [
      "Sprecherin: Wann haben Sie sich zuletzt gelangweilt? Ich meine nicht die kurze Ungeduld an der Supermarktkasse, die wir reflexhaft mit einem Blick aufs Handy vertreiben. Ich meine jene zähe, fast körperlich spürbare Leere eines verregneten Sonntagnachmittags, an die sich viele nur noch aus der Kindheit erinnern.",
      "Sprecherin: Die Langeweile hat keinen guten Ruf. Sie gilt als Zeichen von Ideenlosigkeit, bei Kindern gar als Versäumnis der Eltern, die offenbar nicht für ausreichend Beschäftigung gesorgt haben. Umso bemerkenswerter ist, dass sich die Psychologie in den letzten Jahren zunehmend für sie interessiert, und zwar keineswegs nur als Problem. Dabei lebt inzwischen ein ganzer Wirtschaftszweig davon, dass wir keinen Moment mehr ungenutzt verstreichen lassen: Podcasts für den Weg zur Arbeit, Spiele für das Wartezimmer, kurze Videos für die zwei Minuten an der Ampel.",
      "Sprecherin: In einem vielzitierten Experiment mussten Versuchspersonen zunächst eine eintönige Aufgabe erledigen, nämlich Telefonnummern aus einem Verzeichnis abschreiben. Anschließend sollten sie sich möglichst viele Verwendungszwecke für zwei Plastikbecher ausdenken. Wer sich vorher gelangweilt hatte, war dabei einfallsreicher als die Vergleichsgruppe.",
      "Sprecherin: Man sollte solche Befunde freilich nicht überstrapazieren. Aus einem Laborversuch folgt noch lange nicht, dass jede Wartezeit ein kreativer Segen ist. Chronische Langeweile, etwa in einem Beruf, der einen dauerhaft unterfordert, kann durchaus krank machen.",
      "Sprecherin: Und doch drängt sich eine Frage auf: Was geht uns verloren, wenn wir jede Lücke im Tag sofort füllen? Möglicherweise nicht die Langeweile selbst, sondern das, was sie gelegentlich hervorbringt: den abschweifenden Gedanken, die unerwartete Verbindung, den Einfall, den man nicht gesucht hat. Vielleicht wäre es also einen Versuch wert, das Telefon beim nächsten Warten einfach in der Tasche zu lassen. Nicht aus Prinzip, sondern aus Neugier.",
    ],
  ),
  clip(
    "l-c2-denkmal",
    "C2",
    "Gespräch: Solaranlagen auf alten Dächern",
    "Umwelt und Kultur",
    [
      { label: "Moderator", voice: "B" },
      { label: "Frau Hartung", voice: "A" },
    ],
    [
      "Moderator: Frau Hartung, Hausbesitzer in historischen Altstädten beklagen seit Jahren, dass ihnen der Denkmalschutz Solaranlagen auf dem Dach verbietet. Sind Sie als Denkmalpflegerin die Bremse der Energiewende?",
      "Frau Hartung: Diese Rolle wird uns gern zugeschrieben, und ich gebe zu, dass wir sie in der Vergangenheit nicht immer zu Unrecht innehatten. Da wurden Anträge abgelehnt, die man mit etwas mehr Fantasie hätte genehmigen können. Inzwischen hat sich die Rechtslage allerdings geändert. Erneuerbare Energien gelten nun ausdrücklich als überragendes öffentliches Interesse, und das verschiebt die Abwägung erheblich.",
      "Moderator: Das heißt, im Zweifel gewinnt das Klima?",
      "Frau Hartung: Im Zweifel wird genauer hingeschaut, wie beides zusammengeht. Das ist ein Unterschied. Auf einem Hinterhofdach, das man von keiner Straße aus sieht, ist eine Anlage heute in aller Regel kein Problem. Bei einer Kirche, die seit fünfhundert Jahren die Silhouette einer Stadt prägt, sieht die Sache anders aus. Da reden wir nicht über persönlichen Geschmack, sondern über ein Zeugnis, das nicht nur uns gehört, sondern auch den Generationen nach uns.",
      "Moderator: Kritiker würden sagen: Genau diese Generationen haben mehr von einem stabilen Klima als von einer unversehrten Dachlandschaft.",
      "Frau Hartung: Das Argument ist nicht von der Hand zu weisen, aber es unterstellt einen Gegensatz, den es so selten gibt. Der Beitrag einiger Dutzend denkmalgeschützter Dächer zur Energiebilanz eines Landes ist verschwindend gering. Der Verlust eines unverwechselbaren Stadtbildes dagegen ist unumkehrbar. Hinzu kommt, dass in einem Altbau, der erhalten und weiter genutzt wird, bereits eine enorme Menge Energie steckt, die ein Neubau erst wieder aufwenden müsste. Denkmalpflege ist, so gesehen, schon immer eine Form von Nachhaltigkeit gewesen.",
    ],
  ),
];

const items: SeedItem[] = [
  // ---------------------------------------------------------------- A1
  choice("A1", "l-a1-bahnhof", "gist", "EASY",
    "Worum geht es in der Durchsage?",
    "Der Zug fährt heute von einem anderen Gleis.",
    ["Der Zug hat eine Stunde Verspätung.", "Der Zug fällt heute aus."],
    1,
    "Die Durchsage nennt nur einen Gleiswechsel, von Gleis 3 zu Gleis 5. Verspätung oder Ausfall werden nicht erwähnt."),
  choice("A1", "l-a1-bahnhof", "detail", "EASY",
    "Von welchem Gleis fährt der Zug nach Hamburg heute ab?",
    "Gleis 5",
    ["Gleis 3", "Gleis 4"],
    2,
    "Gleis fünf wird zweimal genannt. Gleis drei ist das normale Gleis, heute aber nicht."),
  choice("A1", "l-a1-bahnhof", "detail", "MID",
    "Um wie viel Uhr fährt der Zug ab?",
    "um 10.15 Uhr",
    ["um 10.50 Uhr", "um 11.15 Uhr"],
    0,
    "Zehn Uhr fünfzehn = 10.15 Uhr. Fünfzehn und fünfzig klingen ähnlich, darauf achten."),

  choice("A1", "l-a1-cafe", "detail", "EASY",
    "Was trinkt der Gast?",
    "Kaffee und Wasser",
    ["Tee und Wasser", "Kaffee und Saft"],
    1,
    "Der Gast sagt: Einen Kaffee, bitte. Und ein Wasser."),
  choice("A1", "l-a1-cafe", "detail", "MID",
    "Wie viel kostet alles zusammen?",
    "8,50 Euro",
    ["10,00 Euro", "5,80 Euro", "18,50 Euro"],
    3,
    "Die Kellnerin sagt acht Euro fünfzig. Zehn Euro gibt der Gast, das ist nicht der Preis."),
  tfng("A1", "l-a1-cafe", "detail", "HARD",
    [
      ["Der Gast isst ein Stück Kuchen.", "R"],
      ["Der Gast bestellt eine Suppe.", "F"],
      ["Der Gast kommt jeden Tag in dieses Café.", "NG"],
    ],
    "Apfelkuchen wird bestellt, eine Suppe nicht. Ob der Gast oft kommt, sagt das Gespräch nicht."),

  choice("A1", "l-a1-party", "gist", "EASY",
    "Warum ruft Lena an?",
    "Sie lädt Tom zu einer Party ein.",
    ["Sie kann am Samstag nicht kommen.", "Sie hat eine neue Adresse."],
    2,
    "Lena sagt: Ich mache am Samstag eine kleine Party. Die Adresse nennt sie nur für die Party."),
  choice("A1", "l-a1-party", "detail", "MID",
    "Wann beginnt die Party?",
    "am Samstag um 20 Uhr",
    ["am Freitag um 20 Uhr", "am Samstag um 18 Uhr"],
    1,
    "Acht Uhr am Abend ist 20 Uhr, der Tag ist Samstag."),
  choice("A1", "l-a1-party", "detail", "MID",
    "Was soll Tom mitbringen?",
    "Musik",
    ["Getränke", "Kuchen"],
    0,
    "Lena fragt: Kannst du bitte Musik mitbringen?"),

  // ---------------------------------------------------------------- A2
  choice("A2", "l-a2-arzt", "gist", "EASY",
    "Warum ruft Herr Demir in der Praxis an?",
    "Er ist krank und braucht einen Termin.",
    ["Er möchte ein Rezept abholen.", "Er möchte einen Termin absagen."],
    0,
    "Er sagt gleich am Anfang: Ich brauche bitte einen Termin, und nennt Halsschmerzen und Fieber."),
  choice("A2", "l-a2-arzt", "detail", "MID",
    "Wann hat Herr Demir seinen Termin?",
    "morgen um 15.15 Uhr",
    ["morgen um 9 Uhr", "heute um 15.15 Uhr", "morgen um 15.45 Uhr"],
    2,
    "Neun Uhr passt ihm nicht, weil er arbeitet. Viertel nach drei am Nachmittag ist 15.15 Uhr, und zwar morgen."),
  tfng("A2", "l-a2-arzt", "detail", "HARD",
    [
      ["Herr Demir ist seit einer Woche krank.", "F"],
      ["Er soll seine Versichertenkarte mitbringen.", "R"],
      ["Herr Demir war schon oft in dieser Praxis.", "NG"],
    ],
    "Er ist seit drei Tagen krank, nicht seit einer Woche. Die Karte soll er mitbringen. Ob er die Praxis kennt, wird nicht gesagt."),

  choice("A2", "l-a2-wochenende", "detail", "EASY",
    "Mit wem war Mia in Köln?",
    "mit ihrer Schwester",
    ["mit ihrer Freundin", "mit ihren Eltern"],
    2,
    "Mia sagt: Am Samstag war ich mit meiner Schwester in Köln."),
  choice("A2", "l-a2-wochenende", "detail", "MID",
    "Wie ist Mia nach Köln gefahren?",
    "mit dem Zug",
    ["mit dem Auto", "mit dem Bus"],
    1,
    "Mia antwortet: Mit dem Zug. Die Fahrt hat eine Stunde gedauert."),
  choice("A2", "l-a2-wochenende", "detail", "MID",
    "Warum ist Jonas am Wochenende zu Hause geblieben?",
    "Er war erkältet.",
    ["Er musste arbeiten.", "Das Wetter war schlecht.", "Er hatte Besuch."],
    3,
    "Jonas sagt: Ich war erkältet und bin zu Hause geblieben."),

  choice("A2", "l-a2-supermarkt", "detail", "EASY",
    "Wie viel kostet ein Kilo Tomaten heute?",
    "1,99 Euro",
    ["0,99 Euro", "2,99 Euro"],
    1,
    "Einen Euro neunundneunzig = 1,99 Euro."),
  choice("A2", "l-a2-supermarkt", "detail", "MID",
    "Bis wann gibt es die Brötchen zum halben Preis?",
    "bis 12 Uhr",
    ["bis 22 Uhr", "den ganzen Tag"],
    0,
    "Das Angebot gilt nur bis zwölf Uhr. 22 Uhr ist die neue Schließzeit ab nächster Woche."),
  choice("A2", "l-a2-supermarkt", "gist", "HARD",
    "Was ist ab nächster Woche neu?",
    "Der Markt ist abends länger geöffnet.",
    ["Der Markt ist auch am Sonntag geöffnet.", "Im Markt gibt es eine neue Bäckerei."],
    2,
    "Neu ist: Montag bis Samstag bis 22 Uhr. Sonntags bleibt der Markt geschlossen."),

  // ---------------------------------------------------------------- B1
  choice("B1", "l-b1-wohnung", "detail", "MID",
    "Wie viel muss Sara ungefähr pro Monat zahlen, wenn sie die Wohnung mietet?",
    "etwa 770 Euro",
    ["etwa 650 Euro", "etwa 530 Euro", "etwa 880 Euro"],
    0,
    "Kaltmiete 650 Euro plus etwa 120 Euro Nebenkosten ergibt ungefähr 770 Euro."),
  tfng("B1", "l-b1-wohnung", "detail", "MID",
    [
      ["Die Wohnung hat einen Balkon.", "F"],
      ["Sara darf ihre Katze mitbringen.", "R"],
      ["Die Wohnung liegt im Erdgeschoss.", "NG"],
      ["Die Mieter dürfen den Garten benutzen.", "R"],
    ],
    "Kein Balkon, aber Garten. Katzen sind erlaubt, Hunde nicht. Das Stockwerk wird nicht genannt."),
  choice("B1", "l-b1-wohnung", "detail", "HARD",
    "Wie findet die Besichtigung statt?",
    "Sara sieht die Wohnung am Donnerstag zusammen mit anderen Interessenten.",
    [
      "Sara besichtigt die Wohnung am Donnerstag allein.",
      "Frau Lorenz schickt Sara zuerst Fotos von der Wohnung.",
      "Sara soll am Donnerstag noch einmal anrufen.",
    ],
    3,
    "Frau Lorenz zeigt die Wohnung am Donnerstag um halb sechs mehreren Interessenten, Sara soll dazukommen."),

  choice("B1", "l-b1-wochenendtipps", "gist", "EASY",
    "Worum geht es in dem Beitrag?",
    "um Freizeittipps für das Wochenende",
    ["um aktuelle Verkehrsmeldungen", "um die Wettervorhersage für die ganze Woche"],
    0,
    "Die Moderatorin kündigt Tipps fürs Wochenende an. Verkehr und Wetter kommen nur am Rand vor."),
  choice("B1", "l-b1-wochenendtipps", "detail", "MID",
    "Warum sollen Besucher des Stadtfests lieber mit Bus oder Bahn kommen?",
    "Die Innenstadt ist für Autos gesperrt.",
    ["Die Busse sind am Wochenende kostenlos.", "Am Marktplatz gibt es zu wenige Parkplätze."],
    2,
    "Die Innenstadt ist ab Freitagabend gesperrt. Dass Busse kostenlos sind oder Parkplätze fehlen, wird nicht gesagt."),
  choice("B1", "l-b1-wochenendtipps", "detail", "HARD",
    "Was muss man bei der Führung im Stadtmuseum beachten?",
    "Man muss sich vorher anmelden.",
    ["Sie kostet Eintritt.", "Sie findet am Samstag statt.", "Sie ist nur für Kinder."],
    1,
    "Die Führung ist kostenlos und am Sonntag, aber nur für zwanzig Personen, deshalb ist eine Anmeldung nötig."),

  choice("B1", "l-b1-abschied", "gist", "EASY",
    "Warum planen Daniel und Petra ein Fest?",
    "Herr Schulte geht in Rente.",
    ["Herr Schulte hat Geburtstag.", "Herr Schulte wechselt die Firma."],
    2,
    "Petra sagt: Er geht ja Ende des Monats in Rente."),
  choice("B1", "l-b1-abschied", "detail", "MID",
    "Wo findet das Fest am Ende statt?",
    "in der Kantine",
    ["im Restaurant am See", "bei Herrn Schulte zu Hause"],
    1,
    "Das Restaurant ist zu teuer. Sie feiern in der Kantine, jeder bringt etwas zu essen mit."),
  choice("B1", "l-b1-abschied", "detail", "HARD",
    "Welche Aufgabe übernimmt Petra?",
    "Sie besorgt einen Gutschein für ein Hotel.",
    ["Sie schreibt die Einladung an alle.", "Sie sammelt noch mehr Geld.", "Sie reserviert einen Raum im Restaurant."],
    0,
    "Petra: Ich kümmere mich um den Gutschein. Die Einladung schreibt Daniel."),

  // ---------------------------------------------------------------- B2
  choice("B2", "l-b2-homeoffice", "attitude", "HARD",
    "Wie beurteilt Frau Albers die Rückkehr ins Büro?",
    "Sie findet sie sinnvoll, wenn die Treffen einen klaren Zweck haben und nicht der Kontrolle dienen.",
    [
      "Sie lehnt sie grundsätzlich ab, weil man zu Hause konzentrierter arbeitet.",
      "Sie hält sie für nötig, weil Beschäftigte zu Hause weniger leisten.",
      "Sie äußert dazu keine eigene Meinung.",
    ],
    3,
    "Sie sagt teilweise ja: problematisch bei Kontrolle, sinnvoll, wenn man gemeinsam festlegt, wofür man sich trifft."),
  choice("B2", "l-b2-homeoffice", "detail", "MID",
    "Wofür kommen viele Teams laut Frau Albers an zwei Tagen pro Woche zusammen?",
    "für Besprechungen, Workshops und die Einarbeitung neuer Kollegen",
    ["für gemeinsame Pausen in der Kaffeeküche", "für die Kontrolle der Arbeitszeiten"],
    2,
    "Das wird ausdrücklich genannt. Die Kaffeeküche erwähnt sie nur als Ort spontaner Ideen."),
  tfng("B2", "l-b2-homeoffice", "detail", "MID",
    [
      ["Laut Frau Albers leidet im Homeoffice vor allem das konzentrierte Arbeiten.", "F"],
      ["Fast die Hälfte der Befragten liest abends noch dienstliche E-Mails.", "R"],
      ["Frau Albers arbeitet selbst überwiegend von zu Hause aus.", "NG"],
    ],
    "Konzentriertes Arbeiten funktioniert zu Hause gut, es leiden die spontanen Gespräche. Über ihre eigene Arbeitsweise sagt sie nichts."),

  choice("B2", "l-b2-altstadt", "attitude", "MID",
    "Welche Haltung hat Frau Heinemann zu dem Plan?",
    "Sie ist grundsätzlich offen, fürchtet aber, Kundschaft zu verlieren.",
    ["Sie lehnt den Plan entschieden ab.", "Sie ist begeistert und sieht keine Probleme."],
    0,
    "Ihr gefällt die ruhigere Altstadt, doch sie sorgt sich um Kundinnen aus den Dörfern."),
  choice("B2", "l-b2-altstadt", "detail", "MID",
    "Was plant die Stadt für Besucher, die mit dem Auto kommen?",
    "Sie parken am Stadtrand und fahren mit einem kostenlosen Shuttlebus ins Zentrum.",
    [
      "Sie dürfen morgens bis zehn Uhr in die Altstadt fahren.",
      "Sie erhalten eine Sondergenehmigung.",
      "Sie bekommen Rabatt im Einkaufszentrum.",
    ],
    1,
    "Bis zehn Uhr gilt nur für den Lieferverkehr, Sondergenehmigungen nur für Anwohner."),
  choice("B2", "l-b2-altstadt", "attitude", "HARD",
    "Was möchte Frau Heinemann mit ihrem letzten Beitrag erreichen?",
    "dass die Händler schon während des Versuchs nach ihren Erfahrungen gefragt werden",
    [
      "dass der Versuch um ein Jahr verschoben wird",
      "dass mehr Busse in die umliegenden Dörfer fahren",
      "dass die Stadt am Stadtrand mehr Parkplätze baut",
    ],
    3,
    "Sie wünscht eine Befragung nach sechs Monaten statt erst am Ende. Herr Roth sagt eine Zwischenbilanz zu."),

  choice("B2", "l-b2-roman", "attitude", "MID",
    "Wie beurteilt die Kritikerin den Roman insgesamt?",
    "als lesenswert, trotz Schwächen im Mittelteil",
    ["als gelungenes Werk ohne Schwächen", "als Enttäuschung, die man nicht lesen muss"],
    2,
    "Ihr Fazit: kein perfektes Buch, aber ein lesenswertes."),
  choice("B2", "l-b2-roman", "detail", "EASY",
    "Was kritisiert sie am Mittelteil des Romans?",
    "zu viele Rückblenden und unklare Nebenfiguren",
    ["unnatürliche Dialoge", "ein zu schnelles Ende"],
    1,
    "Die Dialoge lobt sie ausdrücklich, und das Ende hat sie berührt."),
  tfng("B2", "l-b2-roman", "detail", "HARD",
    [
      ["Das erste Buch der Autorin war wenig erfolgreich.", "F"],
      ["Im Roman treffen sich drei Geschwister im Haus ihrer verstorbenen Mutter.", "R"],
      ["Die Autorin hat fünf Jahre an dem Roman gearbeitet.", "NG"],
      ["Die Kritikerin empfiehlt das Buch vor allem ungeduldigen Lesern.", "F"],
    ],
    "Das Debüt war ein Überraschungserfolg. Wer Geduld mitbringt, wird belohnt, also nicht für Ungeduldige. Zur Arbeitszeit sagt sie nichts."),

  // ---------------------------------------------------------------- C1
  choice("C1", "l-c1-vorlesung", "gist", "MID",
    "Worum geht es der Professorin in erster Linie?",
    "Sie erklärt, warum Lernende wirksame Methoden oft unterschätzen.",
    [
      "Sie stellt eine neue Technik zum Markieren von Texten vor.",
      "Sie kritisiert, dass Studierende zu wenig Zeit ins Lernen investieren.",
      "Sie bespricht die Ergebnisse der letzten Klausur.",
    ],
    0,
    "Ihre Leitfrage: Warum lernen viele mit Methoden, die wenig bringen? Antwort: Vertrautheit wird mit Wissen verwechselt."),
  choice("C1", "l-c1-vorlesung", "detail", "MID",
    "Was zeigte die Studie eine Woche nach dem Lernen?",
    "Die Gruppe, die sich selbst abgefragt hatte, erinnerte deutlich mehr.",
    [
      "Beide Gruppen erinnerten sich gleich gut.",
      "Die Gruppe, die den Text viermal gelesen hatte, wusste mehr.",
      "Die Teilnehmenden hatten fast alles vergessen.",
    ],
    2,
    "Unmittelbar danach lagen die Vielleser vorn, nach einer Woche hatte sich das Bild umgekehrt."),
  choice("C1", "l-c1-vorlesung", "inference", "HARD",
    "Was lässt sich über die Studierenden schließen, die den Text viermal gelesen hatten?",
    "Sie schätzten ihren Lernerfolg zu optimistisch ein.",
    [
      "Sie hatten weniger Zeit zum Lernen.",
      "Sie hatten den Text gründlicher verstanden.",
      "Sie lehnten das Abfragen aus Prinzip ab.",
    ],
    3,
    "Sie waren sich ihrer Sache sicherer, erinnerten aber später weniger: Selbstüberschätzung, nicht direkt ausgesprochen."),

  choice("C1", "l-c1-land", "detail", "MID",
    "Wohin ziehen laut Herrn Brenner die meisten Menschen, die die Kernstädte verlassen?",
    "in Gemeinden, von denen aus man die Stadt in etwa einer Stunde erreicht",
    ["in abgelegene Dörfer", "in andere Großstädte", "in Kleinstädte an der Küste"],
    1,
    "Er nennt den Speckgürtel. Abgelegene Dörfer profitieren kaum."),
  choice("C1", "l-c1-land", "inference", "HARD",
    "Was deutet Herr Brenner über Fördergeld für Dörfer an?",
    "Es kann allein nicht bewirken, dass sich Zugezogene aufgenommen fühlen.",
    [
      "Es ist die wichtigste Maßnahme gegen Leerstand.",
      "Es sollte vor allem in den Bau neuer Häuser fließen.",
      "Es hat in den meisten Gemeinden bereits Erfolg gehabt.",
    ],
    2,
    "Entscheidend sei, dass sich Neue willkommen fühlen, und: Das lässt sich nicht mit Fördergeld lösen."),
  choice("C1", "l-c1-land", "attitude", "MID",
    "Wie lässt sich die Haltung von Herrn Brenner am besten beschreiben?",
    "nüchtern: Das Land kann einen Beitrag leisten, aber nur unter bestimmten Bedingungen.",
    [
      "euphorisch: Das Arbeiten von zu Hause wird die Dörfer wiederbeleben.",
      "resigniert: Für abgelegene Dörfer gibt es keine Zukunft.",
    ],
    1,
    "Er nennt sich selbst realistisch und knüpft den Beitrag des Landes an Bedingungen."),

  choice("C1", "l-c1-viertagewoche", "detail", "EASY",
    "Wie viele der Betriebe wollen die Viertagewoche beibehalten?",
    "dreißig",
    ["zehn", "zwanzig", "vierzig"],
    2,
    "Dreißig der vierzig Betriebe wollen weitermachen, zehn nicht."),
  choice("C1", "l-c1-viertagewoche", "inference", "HARD",
    "Warum lassen sich die Ergebnisse laut Reporter nur begrenzt verallgemeinern?",
    "Die Betriebe hatten sich freiwillig beworben und waren vermutlich ohnehin offen für Neues.",
    [
      "Der Versuch dauerte nur wenige Wochen.",
      "Die Krankheitstage wurden nicht vollständig erfasst.",
      "Es nahmen fast nur Pflegeeinrichtungen teil.",
    ],
    0,
    "Freiwillige Teilnahme deutet auf eine experimentierfreudige Kultur hin, eine verzerrte Auswahl."),
  choice("C1", "l-c1-viertagewoche", "attitude", "MID",
    "Wie steht der Reporter zur bisherigen Berichterstattung über den Versuch?",
    "Er hält manche Schlagzeilen für zu euphorisch.",
    [
      "Er findet sie zu zurückhaltend.",
      "Er hält sie für ausgewogen und zutreffend.",
      "Er äußert sich nicht dazu.",
    ],
    3,
    "Die Ergebnisse seien differenzierter als die Schlagzeilen, das Fazit weniger spektakulär, aber näher an der Wahrheit."),

  // ---------------------------------------------------------------- C2
  choice("C2", "l-c2-handschrift", "gist", "MID",
    "Worin nähern sich die beiden am Ende an?",
    "Eine lesbare Handschrift soll Grundlage bleiben, ohne jahrelanges Üben einer bestimmten Schreibschrift.",
    [
      "Kinder sollen weiterhin jahrelang Schreibschrift üben.",
      "Handschrift soll im Unterricht durch Programmieren ersetzt werden.",
      "Die Entscheidung soll den Eltern überlassen werden.",
    ],
    1,
    "Frau Seidel ist die verbundene Schrift gleichgültig, Herr Kranz akzeptiert eine lesbare Handschrift als Grundlage."),
  choice("C2", "l-c2-handschrift", "attitude", "HARD",
    "Wie geht Herr Kranz mit den Studien um, die Frau Seidel anführt?",
    "Er erkennt sie an, hält ihre Aussagekraft aber für begrenzt.",
    [
      "Er bestreitet, dass es solche Studien gibt.",
      "Er übernimmt ihre Schlussfolgerungen vollständig.",
      "Er wirft Frau Seidel vor, sie falsch wiederzugeben.",
    ],
    0,
    "Er kennt die Studien, nennt sie aber klein und die Effekte bescheiden."),
  tfng("C2", "l-c2-handschrift", "inference", "HARD",
    [
      ["Herr Kranz bestreitet den kulturellen Wert der Handschrift.", "F"],
      ["Frau Seidel besteht darauf, dass Kinder eine verbundene Schreibschrift lernen.", "F"],
      ["Laut Frau Seidel zwingt das Mitschreiben von Hand dazu, Gehörtes zu verdichten.", "R"],
      ["Frau Seidel unterrichtet selbst an einer Grundschule.", "NG"],
    ],
    "Kranz räumt den kulturellen Wert ausdrücklich ein. Seidel ist die verbundene Schrift gleichgültig. Ihr Beruf wird nicht genannt."),

  choice("C2", "l-c2-langeweile", "gist", "MID",
    "Was ist die Hauptaussage des Beitrags?",
    "Langeweile kann gelegentlich produktiv sein, sollte aber nicht verklärt werden.",
    [
      "Langeweile sollte man möglichst vermeiden.",
      "Kinder langweilen sich heute häufiger als früher.",
      "Das Smartphone ist die Hauptursache chronischer Langeweile.",
    ],
    3,
    "Der Beitrag würdigt die Langeweile, warnt aber davor, Laborbefunde zu überstrapazieren."),
  choice("C2", "l-c2-langeweile", "detail", "EASY",
    "Was mussten die Versuchspersonen nach der eintönigen Aufgabe tun?",
    "sich möglichst viele Verwendungszwecke für zwei Plastikbecher ausdenken",
    ["Telefonnummern auswendig lernen", "einen Fragebogen zu ihrer Stimmung ausfüllen"],
    1,
    "Das Abschreiben der Telefonnummern war die langweilige Aufgabe davor."),
  choice("C2", "l-c2-langeweile", "inference", "HARD",
    "Was meint die Sprecherin, wenn sie empfiehlt, das Telefon nicht aus Prinzip, sondern aus Neugier in der Tasche zu lassen?",
    "Sie regt einen offenen Selbstversuch an, ohne daraus eine Regel zu machen.",
    [
      "Sie fordert einen konsequenten Verzicht auf das Smartphone.",
      "Sie hält Smartphones grundsätzlich für schädlich.",
      "Sie möchte, dass die Hörer an einer Studie teilnehmen.",
    ],
    2,
    "Nicht aus Prinzip: kein Dogma. Aus Neugier: ausprobieren, was passiert."),

  choice("C2", "l-c2-denkmal", "attitude", "HARD",
    "Wie reagiert Frau Hartung auf den Vorwurf, die Denkmalpflege bremse die Energiewende?",
    "Sie räumt frühere Versäumnisse ein und verweist auf die veränderte Rechtslage.",
    [
      "Sie weist ihn empört zurück.",
      "Sie stimmt ihm uneingeschränkt zu.",
      "Sie geht nicht darauf ein.",
    ],
    0,
    "Sie gibt zu, dass die Rolle nicht immer zu Unrecht zugeschrieben wurde, und nennt die neue Rechtslage."),
  choice("C2", "l-c2-denkmal", "inference", "HARD",
    "Was drückt Frau Hartung mit dem Satz aus, im Zweifel werde genauer hingeschaut, wie beides zusammengeht?",
    "Der Klimaschutz setzt sich nicht automatisch durch, es wird im Einzelfall abgewogen.",
    [
      "Der Denkmalschutz hat grundsätzlich Vorrang.",
      "Die Behörden entscheiden inzwischen schneller.",
      "Anträge werden nur noch bei Kirchen abgelehnt.",
    ],
    3,
    "Sie widerspricht dem Moderator: nicht Klima gewinnt, sondern genauere Abwägung. Beispiel Hinterhofdach gegenüber Kirche."),
  choice("C2", "l-c2-denkmal", "detail", "MID",
    "Mit welchem Argument stellt Frau Hartung die Denkmalpflege als nachhaltig dar?",
    "In einem erhaltenen Altbau steckt bereits Energie, die ein Neubau erst aufwenden müsste.",
    [
      "Alte Gebäude verbrauchen weniger Heizenergie als neue.",
      "Denkmalgeschützte Dächer eignen sich besonders gut für Solaranlagen.",
      "Altbauten werden ausschließlich mit natürlichen Materialien saniert.",
    ],
    2,
    "Es geht um die im Bestand gebundene Energie, nicht um den Heizverbrauch."),
];

export const listening: SeedBankPart = { stimuli, items };
